version: 2

# Location of the conf.py
sphinx:
  configuration: docs/source/conf.py

# Conda environment
conda:
  environment: docs/source/environment.yml

python:
  version: 3.6
  install:
    - method: setuptools
      path: .

